<html>

<head>
    <title>Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <script src="
    https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
    "></script>
    <script src="
    https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.js
    "></script>
    <link href="
    https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.css
    " rel="stylesheet">
    <script src="
    https://cdn.jsdelivr.net/npm/cytoscape@3.28.0/dist/cytoscape.min.js
    "></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
</head>

<body>
<div class="ui container" id="main" style="margin-top: 20px; margin-bottom: 20px;">

    <div id="content" style="margin-bottom: 20px; margin-top: 20px;">
        <div class="ui clearing segment toplevel">
            <h2 class="ui header">
                Index
            </h2>

            <#list subjects as subject>
                <a href="${subject}/RANK.html">${subject}</a> <br/>
            </#list>

            <i>Generated by Rating Everything, XGN from Hell Hole Studios 2023-2024</i>
        </div>

    </div>
</div>

<script>

        //play animation
        $('.ui.segment .item').transition('hide')
        $('.ui.segment.toplevel')
            .transition('hide')
            .transition({
                animation: 'scale in',
                reverse: 'auto', // default setting
                interval: 200,
                onComplete: function () {
                    // console.log(this)
                    $(this).find('.item')
                        .transition({
                            animation: 'scale in',
                            reverse: 'auto',
                            interval: 100
                        });

                    $('.ui.sticky').sticky({ context: '#content' });
                }
            });


        $('#time').popup({ on: 'focus' });
</script>
</body>

</html>